# Generated by Django 5.2.6 on 2025-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eng_w',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.CharField(max_length=50)),
                ('t', models.CharField(max_length=50)),
            ],
        ),
    ]
